params = {
        "BTC/USDT": {
            "src": "close",
            "ma_base_window": 7,
            "envelopes": [0.07, 0.09, 0.12],
            "size": 0.1,
            "sides": ["long", "short"],
        },
        "ETH/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.07, 0.09, 0.12],
            "size": 0.1,
            "sides": ["long", "short"],
        },
        "ADA/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "AVAX/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "SOL/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "MATIC/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "XRP/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "LINK/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "LTC/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "ATOM/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "NEAR/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "ARB/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.1],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "TIA/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "ALGO/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "FIL/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "APT/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "INJ/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "SAND/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "TRX/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
        "XTZ/USDT": {
            "src": "close",
            "ma_base_window": 5,
            "envelopes": [0.09, 0.12, 0.15],
            "size": 0.05,
            "sides": ["long", "short"],
        },
}